name: process-pending

on:
  issues:
    types: [edited]
  issue_comment:
    types: [created, edited, deleted]

jobs:
  process-pending:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v2
        with:
          github-token: ${{secrets.BOTS_PAT}}
          script: |
            const path = require('path')
            const scriptPath = path.resolve('./.github/workflows/process-pending.js')
            require(scriptPath)({context, github, io, core})
